"""empty message

Revision ID: 152acb6b0699
Revises: 
Create Date: 2023-06-30 07:06:08.859840

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '152acb6b0699'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=100), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('task', schema=None) as batch_op:
        batch_op.drop_column('email')

    # ### end Alembic commands ###
